name: Android Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TOOLS: "35.0.0"
      ANDROID_PLATFORM: "android-35"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Aceptar licencias SDK
        run: yes | sdkmanager --licenses

      - name: Instalar componentes del SDK
        run: |
          sdkmanager "build-tools;${BUILD_TOOLS}" "platforms;${ANDROID_PLATFORM}" "platform-tools" "cmdline-tools;latest"

      - name: Crear keystore desde secret (opcional)
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Escribir credenciales de firma
        run: |
          cat >> ./gradle.properties <<'EOF'
          MYAPP_UPLOAD_STORE_FILE=keystore.jks
          MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew

      - name: Build release
        run: ./gradlew --no-daemon assembleRelease

      - name: Subir APK como artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk
