import groovy.xml.MarkupBuilder

plugins {
    id 'com.android.application'
}

def twaManifest = [
    applicationId: 'cl.icarticular.app',
    hostName: 'icarticular.cl',
    launchUrl: '/',
    name: 'Asistente ICA',
    launcherName: 'ICA',
    themeColor: '#0EA5E9',
    themeColorDark: '#000000',
    navigationColor: '#000000',
    navigationColorDark: '#000000',
    navigationDividerColor: '#000000',
    navigationDividerColorDark: '#000000',
    backgroundColor: '#FFFFFF',
    enableNotifications: true,
    shortcuts: [],
    splashScreenFadeOutDuration: 300,
    generatorApp: 'bubblewrap-cli',
    fallbackType: 'customtabs',
    enableSiteSettingsShortcut: 'true',
    orientation: 'default',
]

android {
    // Recomendado para CI estable
    compileSdkVersion 35

    namespace "cl.icarticular.app"

    defaultConfig {
        applicationId "cl.icarticular.app"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "1"

        resValue "string", "appName", twaManifest.name
        resValue "string", "launcherName", twaManifest.launcherName

        def launchUrl = "https://" + twaManifest.hostName + twaManifest.launchUrl
        resValue "string", "launchUrl", launchUrl

        // Web manifest / scope (tu PWA en Vercel)
        resValue "string", "webManifestUrl", 'https://asistencia-ica.vercel.app/manifest.webmanifest'
        resValue "string", "fullScopeUrl", 'https://asistencia-ica.vercel.app/'

        // host para el intent-filter
        resValue "string", "hostName", twaManifest.hostName

        // Colores
        resValue "color", "colorPrimary", twaManifest.themeColor
        resValue "color", "colorPrimaryDark", twaManifest.themeColorDark
        resValue "color", "navigationColor", twaManifest.navigationColor
        resValue "color", "navigationColorDark", twaManifest.navigationColorDark
        resValue "color", "navigationDividerColor", twaManifest.navigationDividerColor
        resValue "color", "navigationDividerColorDark", twaManifest.navigationDividerColorDark
        resValue "color", "backgroundColor", twaManifest.backgroundColor

        // Splash provider
        resValue "string", "providerAuthority", twaManifest.applicationId + '.fileprovider'

        // Notificaciones delegadas
        resValue "bool", "enableNotification", twaManifest.enableNotifications.toString()

        // Shortcuts (si los usas)
        twaManifest.shortcuts.eachWithIndex { shortcut, index ->
            resValue "string", "shortcut_name_$index", "$shortcut.name"
            resValue "string", "shortcut_short_name_$index", "$shortcut.short_name"
        }

        // Animación splash
        resValue "integer", "splashScreenFadeOutDuration", twaManifest.splashScreenFadeOutDuration.toString()

        resValue "string", "generatorApp", twaManifest.generatorApp
        resValue "string", "fallbackType", twaManifest.fallbackType
        resValue "bool", "enableSiteSettingsShortcut", twaManifest.enableSiteSettingsShortcut
        resValue "string", "orientation", twaManifest.orientation
    }

    // === FIRMA PARA CI (lee de gradle.properties en ~/.gradle o del proyecto) ===
    signingConfigs {
        release {
            // El workflow de Actions crea "keystore.jks" en la raíz del repo
            def storeFilePath = project.findProperty("MYAPP_UPLOAD_STORE_FILE") ?: "keystore.jks"
            storeFile file(storeFilePath)
            storePassword project.findProperty("MYAPP_UPLOAD_STORE_PASSWORD") ?: ""
            keyAlias project.findProperty("MYAPP_UPLOAD_KEY_ALIAS") ?: ""
            keyPassword project.findProperty("MYAPP_UPLOAD_KEY_PASSWORD") ?: ""
        }
    }

    buildTypes {
        release {
            // Para el primer build en CI, si quieres facilitarlo:
            // minifyEnabled false
            minifyEnabled true
            // shrinkResources true  // opcional si activas minify
            signingConfig signingConfigs.release
            // Si usas ProGuard:
            // proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            // No firmamos debug con keystore de release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        checkReleaseBuilds false
    }
}

task generateShorcutsFile {
    assert twaManifest.shortcuts.size() < 5, "You can have at most 4 shortcuts."
    twaManifest.shortcuts.eachWithIndex { s, i ->
        assert s.name != null, 'Missing `name` in shortcut #' + i
        assert s.short_name != null, 'Missing `short_name` in shortcut #' + i
        assert s.url != null, 'Missing `icon` in shortcut #' + i
        assert s.icon != null, 'Missing `url` in shortcut #' + i
    }

    def shortcutsFile = new File("$projectDir/src/main/res/xml", "shortcuts.xml")

    def xmlWriter = new StringWriter()
    def xmlMarkup = new MarkupBuilder(new IndentPrinter(xmlWriter, "    ", true))

    xmlMarkup.'shortcuts'('xmlns:android': 'http://schemas.android.com/apk/res/android') {
        twaManifest.shortcuts.eachWithIndex { s, i ->
            'shortcut'(
                'android:shortcutId': 'shortcut' + i,
                'android:enabled': 'true',
                'android:icon': '@drawable/' + s.icon,
                'android:shortcutShortLabel': '@string/shortcut_short_name_' + i,
                'android:shortcutLongLabel': '@string/shortcut_name_' + i
            ) {
                'intent'(
                    'android:action': 'android.intent.action.MAIN',
                    'android:targetPackage': twaManifest.applicationId,
                    'android:targetClass': twaManifest.applicationId + '.LauncherActivity',
                    'android:data': s.url
                )
                'categories'('android:name': 'android.intent.category.LAUNCHER')
            }
        }
    }
    shortcutsFile.text = xmlWriter.toString() + '\n'
}

preBuild.dependsOn(generateShorcutsFile)

repositories {
    // (vacío está bien)
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.6.2'
}
