name: Android Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Solo instalamos cmdline-tools y aceptamos licencias.
      # Gradle invocará sdkmanager por su cuenta para bajar plataformas/build-tools que falten.
      - name: Set up Android SDK (accept licenses)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle info
        run: ./gradlew --version

      - name: Assemble release APK
        run: ./gradlew :app:assembleRelease --stacktrace --no-daemon

      # Si más adelante quieres AAB, descomenta este bloque:
      # - name: Bundle release (AAB)
      #   run: ./gradlew :app:bundleRelease --stacktrace --no-daemon

      - name: List outputs
        run: |
          echo "== outputs =="
          find app/build/outputs -type f -printf "%p\n" || true

      - name: Upload artifacts (APK/AAB)
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/bundle/**/*.aab
          if-no-files-found: error
