name: Android Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Instalación del SDK + aceptación de licencias dentro del mismo paso
      - name: Set up Android SDK (accept licenses)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: |
            platforms;android-35
            build-tools;35.0.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # --- Construir APK release ---
      - name: Assemble release APK
        run: ./gradlew :app:assembleRelease --stacktrace --no-daemon

      # --- (Opcional) construir AAB release ---
      # - name: Bundle release (AAB)
      #   run: ./gradlew :app:bundleRelease --stacktrace --no-daemon

      # Mostrar qué se generó para verificar rutas
      - name: List outputs
        run: |
          echo "== find APK/AAB =="
          find app -type f \( -name "*.apk" -o -name "*.aab" \) -printf "%p\n" || true
          echo "== tree app/build/outputs =="
          ls -R app/build/outputs || true

      # Subir cualquier APK/AAB generado como artefacto
      - name: Upload artifacts (APK/AAB)
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/bundle/**/*.aab
          if-no-files-found: error
